kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: initial-clean-up
  commands:
  - ci-cd/docker/full-clean-up.sh
  when:
    branch:
    - main

- name: test
  commands:
  - ci-cd/docker/build-test.sh
  - ci-cd/docker/test.sh

- name: testing-clean-up
  commands:
  - ci-cd/docker/testing-clean-up.sh

- name: deploy
  commands:
  - ci-cd/docker/build.sh
  - ci-cd/docker/deploy.sh
  when:
    branch:
    - main
