kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: custom-clone
  commands:
  - git init
  - git remote add origin https://github.com/BarBariansAccount/brothers-barbershop-website.git
  - git fetch
  - git checkout $DRONE_REPO_BRANCH

- name: full-clean-up
  commands:
  - ci-cd/docker/full-clean-up.sh

- name: metric-scan
  environment:
    SONAR_TOKEN:
      from_secret: sonar_token
  commands:
  - docker run --rm -e SONAR_HOST_URL="http://localhost:9001/" -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=Brothers-Barbershop" -e SONAR_LOGIN="$SONAR_TOKEN" -v "$PWD:/usr/src" --network=host sonarsource/sonar-scanner-cli

- name: test
  environment:
    PASSWORD:
      from_secret: database_password
  commands:
  - docker network create barber-network-test
  - docker run --name database -v "$PWD/ci-cd/init-db.sh":/docker-entrypoint-initdb.d/init-db.sh -e POSTGRES_PASSWORD=$PASSWORD -e POSTGRES_DB=barbershop -p 5432:5432 --net barber-network-test -d postgres
  - sleep 5
  - docker build --network barber-network-test -t barbershop:backend-test --target test -f "ci-cd/docker/dockerfiles/backend-dockerfile" .
  # docker build --network barber-network-test -t barbershop:frontend-test --target test -f "ci-cd/docker/dockerfiles/frontend-dockerfile" .

- name: testing-clean-up
  commands:
  - ci-cd/docker/testing-clean-up.sh

- name: build
  commands:
  - docker network create barber-network
  - docker build -t barbershop:backend --target production -f "ci-cd/docker/dockerfiles/backend-dockerfile" .
  - docker build -t barbershop:frontend --target production -f "ci-cd/docker/dockerfiles/frontend-dockerfile" .
  when:
    branch:
    - main

- name: deploy
  environment:
    PASSWORD:
      from_secret: database_password
  commands:
  - docker run --name database -v "$PWD/ci-cd/init-db.sh":/docker-entrypoint-initdb.d/init-db.sh -e POSTGRES_PASSWORD=$PASSWORD -e POSTGRES_DB=barbershop --net barber-network -d postgres
  - sleep 5
  - docker run -p 5001:5001 --net barber-network --name backend -d barbershop:backend 
  - docker run -p 7070:8080 --net barber-network --name frontend -d barbershop:frontend
  when:
    branch:
    - main
