kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: clean-up
  commands:
  - ci-cd/docker/clean-up.sh

steps:
- name: test
  commands:
  - ci-cd/docker/build-test.sh
  - ci-cd/docker/test.sh
